name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched [existing issues](https://github.com/Sasstify-AI-Research/sasstify-frontend-template/issues) and feature requests
          required: true
        - label: I have checked the [Roadmap](https://github.com/Sasstify-AI-Research/sasstify-frontend-template/blob/main/ROADMAP.md) to see if this is already planned
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe your feature idea
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        I'm frustrated when...
        I need to...
        Users want to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you implement this feature?
      placeholder: Describe your solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you considered?
      placeholder: Describe alternative approaches
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Component
        - New Hook
        - New Utility
        - Build System Enhancement
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples / Mockups
      description: Provide examples, mockups, or links to similar implementations
      placeholder: |
        - Link to similar feature in other projects
        - Figma mockups
        - Code examples
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful
      placeholder: |
        1. When building...
        2. In scenarios where...
        3. For users who...
    validations:
      required: false

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature would introduce breaking changes
        - label: This feature is backward compatible

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Technical considerations or suggestions for implementation
      placeholder: |
        - Dependencies needed
        - Potential challenges
        - Performance considerations
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature
      placeholder: Any additional information that might help
    validations:
      required: false

