#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Utility functions
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

function toPascalCase(str) {
  return str.split('-').map(word => 
    word.charAt(0).toUpperCase() + word.slice(1)
  ).join('');
}

function toKebabCase(str) {
  return str.toLowerCase().replace(/\s+/g, '-');
}

function validatePageName(name) {
  const kebabRegex = /^[a-z][a-z0-9-]*$/;
  if (!kebabRegex.test(name)) {
    return 'Page name must be kebab-case (lowercase, hyphens only, e.g., "user-profile")';
  }
  return true;
}

// File generators
function generateIndexHtml(pagePath, pageNameKebab, pageTitle, pageDescription) {
  const content = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${pageTitle}</title>
    <meta name="description" content="${pageDescription}" />
  </head>

  <body>
    <div id="root"></div>
    <script type="module" src="/src/pages/${pageNameKebab}/main.tsx"></script>
  </body>
</html>
`;
  
  fs.writeFileSync(path.join(pagePath, 'index.html'), content);
  console.log(`  ✅ Created src/pages/${pageNameKebab}/index.html`);
}

function generateMainTsx(pagePath, pageNameKebab, pageNamePascal) {
  const content = `import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import ${pageNamePascal} from './${pageNamePascal}'

const queryClient = new QueryClient();

createRoot(document.getElementById("root")!).render(
  <QueryClientProvider client={queryClient}>
    <${pageNamePascal} />
  </QueryClientProvider>
);
`;
  
  fs.writeFileSync(path.join(pagePath, 'main.tsx'), content);
  console.log(`  ✅ Created src/pages/${pageNameKebab}/main.tsx`);
}

function generatePageComponent(pagePath, pageNamePascal, pageNameKebab, pageTitle, needsCss) {
  const cssImport = needsCss ? `import styles from './${pageNamePascal}.module.css';\n` : '';
  const cssClass = needsCss ? ` className={styles.container}` : '';
  
  const content = `import Layout from '@/components/layout/Layout';
import { Sparkles, Info, CheckCircle, AlertCircle } from 'lucide-react';
${cssImport}
const ${pageNamePascal} = () => {
  return (
    <Layout fixedHeader={true}>
      <div${cssClass}>
        {/* Hero Section */}
        <section className="bg-gradient-to-r from-blue-50 to-indigo-50 py-16">
          <div className="container mx-auto px-4">
            <div className="flex items-center gap-3 mb-4">
              <Sparkles className="w-8 h-8 text-blue-600" />
              <h1 className="text-4xl font-bold text-gray-900">${pageTitle}</h1>
            </div>
            <p className="text-xl text-gray-600 max-w-2xl">
              This is a test page generated by the create:page script. 
              Edit this content in src/pages/${pageNameKebab}/${pageNamePascal}.tsx
            </p>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-12">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold mb-8 flex items-center gap-2">
              <CheckCircle className="w-6 h-6 text-green-600" />
              Features & Components
            </h2>
            
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {/* Feature Card 1 */}
              <div className="bg-white rounded-lg shadow-lg p-6 border border-gray-200 hover:shadow-xl transition-shadow">
                <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
                  <Sparkles className="w-6 h-6 text-blue-600" />
                </div>
                <h3 className="text-xl font-semibold mb-2">Feature One</h3>
                <p className="text-gray-600">
                  This is a test feature card. Replace with your actual content.
                </p>
              </div>

              {/* Feature Card 2 */}
              <div className="bg-white rounded-lg shadow-lg p-6 border border-gray-200 hover:shadow-xl transition-shadow">
                <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
                  <CheckCircle className="w-6 h-6 text-green-600" />
                </div>
                <h3 className="text-xl font-semibold mb-2">Feature Two</h3>
                <p className="text-gray-600">
                  Add your own components and features here.
                </p>
              </div>

              {/* Feature Card 3 */}
              <div className="bg-white rounded-lg shadow-lg p-6 border border-gray-200 hover:shadow-xl transition-shadow">
                <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
                  <Info className="w-6 h-6 text-purple-600" />
                </div>
                <h3 className="text-xl font-semibold mb-2">Feature Three</h3>
                <p className="text-gray-600">
                  Customize this grid to showcase your page features.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Content Section */}
        <section className="py-12 bg-gray-50">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold mb-6">Content Section</h2>
            <div className="bg-white rounded-lg shadow-lg p-8">
              <p className="text-gray-700 mb-4">
                This is a sample content section. You can add any content here:
              </p>
              <ul className="space-y-2 mb-6">
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-green-600 mt-0.5" />
                  <span className="text-gray-700">Fully responsive layout using Tailwind CSS</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-green-600 mt-0.5" />
                  <span className="text-gray-700">TypeScript support with type safety</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-green-600 mt-0.5" />
                  <span className="text-gray-700">Lucide icons pre-integrated</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-5 h-5 text-green-600 mt-0.5" />
                  <span className="text-gray-700">Fast development with Vite HMR</span>
                </li>
              </ul>
              
              <div className="bg-blue-50 border-l-4 border-blue-600 p-4 rounded">
                <div className="flex items-start gap-3">
                  <Info className="w-5 h-5 text-blue-600 mt-0.5" />
                  <div>
                    <h4 className="font-semibold text-blue-900 mb-1">Getting Started</h4>
                    <p className="text-blue-800 text-sm">
                      Replace this test content with your actual page content. 
                      Check out the other pages (Index, Dashboard) for more examples.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Call to Action */}
        <section className="py-16 bg-gradient-to-r from-purple-50 to-pink-50">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-3xl font-bold mb-4">Ready to Get Started?</h2>
            <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
              Start building your amazing page by editing the component file.
            </p>
            <div className="flex gap-4 justify-center flex-wrap">
              <button className="px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white font-medium rounded-lg transition-colors shadow-lg">
                Primary Action
              </button>
              <button className="px-6 py-3 bg-white hover:bg-gray-50 text-purple-600 font-medium rounded-lg transition-colors shadow-lg border border-purple-200">
                Secondary Action
              </button>
            </div>
          </div>
        </section>

        {/* Navigation */}
        <section className="py-12 border-t border-gray-200">
          <div className="container mx-auto px-4">
            <h3 className="text-lg font-semibold mb-4">Navigate to:</h3>
            <div className="flex flex-wrap gap-4">
              <a 
                href="/" 
                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md transition-colors"
              >
                🏠 Home
              </a>
              <a 
                href="/dashboard/" 
                className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-md transition-colors"
              >
                📊 Dashboard
              </a>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default ${pageNamePascal};
`;
  
  fs.writeFileSync(path.join(pagePath, `${pageNamePascal}.tsx`), content);
  console.log(`  ✅ Created src/pages/${pageNameKebab}/${pageNamePascal}.tsx`);
}

function generateCssFile(pagePath, pageNameKebab, pageNamePascal) {
  const content = `.container {
  min-height: 100vh;
  background: linear-gradient(to bottom, #ffffff, #f9fafb);
}

/* Section Spacing */
.section {
  padding: 3rem 0;
}

/* Custom animations */
@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.fadeIn {
  animation: fadeIn 0.6s ease-out;
}

/* Hover effects */
.card-hover {
  transition: all 0.3s ease;
}

.card-hover:hover {
  transform: translateY(-4px);
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
}

/* Responsive utilities */
@media (max-width: 768px) {
  .section {
    padding: 2rem 0;
  }
}
`;
  
  fs.writeFileSync(path.join(pagePath, `${pageNamePascal}.module.css`), content);
  console.log(`  ✅ Created src/pages/${pageNameKebab}/${pageNamePascal}.module.css`);
}

function generateComponentFile(componentsPath, componentName) {
  const content = `import { LucideIcon } from 'lucide-react';

interface ${componentName}Props {
  title?: string;
  description?: string;
  icon?: LucideIcon;
  variant?: 'default' | 'primary' | 'success' | 'warning';
}

const ${componentName} = ({ 
  title = "Component Title",
  description = "This is a test component generated by the create:page script.",
  icon: Icon,
  variant = 'default' 
}: ${componentName}Props) => {
  
  const variantClasses = {
    default: 'bg-gray-50 border-gray-200 text-gray-900',
    primary: 'bg-blue-50 border-blue-200 text-blue-900',
    success: 'bg-green-50 border-green-200 text-green-900',
    warning: 'bg-yellow-50 border-yellow-200 text-yellow-900',
  };

  return (
    <div className={\`p-6 rounded-lg border-2 \${variantClasses[variant]} transition-all hover:shadow-lg\`}>
      {Icon && (
        <div className="mb-4">
          <Icon className="w-8 h-8" />
        </div>
      )}
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-sm opacity-80">{description}</p>
      
      {/* Example usage area */}
      <div className="mt-4 pt-4 border-t border-current/10">
        <p className="text-xs opacity-60">
          Edit this component in components/${componentName}.tsx
        </p>
      </div>
    </div>
  );
};

export default ${componentName};
`;
  
  fs.writeFileSync(path.join(componentsPath, `${componentName}.tsx`), content);
  console.log(`  ✅ Created component: ${componentName}.tsx`);
}

function updateViteConfig(pageNameKebab) {
  const viteConfigPath = path.join(process.cwd(), 'vite.config.ts');
  let content = fs.readFileSync(viteConfigPath, 'utf8');
  
  let updateCount = 0;
  let warnings = [];
  
  // 1. Add to rollupOptions.input
  const inputPattern = /input:\s*{([^}]+)}/s;
  const inputMatch = content.match(inputPattern);
  
  if (inputMatch) {
    const newEntry = `\n          '${pageNameKebab}': path.resolve(__dirname, 'src/pages/${pageNameKebab}/index.html'),`;
    content = content.replace(inputPattern, (match, entries) => {
      updateCount++;
      return `input: {${entries}${newEntry}\n        }`;
    });
  } else {
    warnings.push('Could not find rollupOptions.input section');
  }
  
  // 2. Add to devServerMiddleware
  // Convert kebab-case to Title Case (e.g., "user-profile" -> "User Profile")
  const pageNameTitle = pageNameKebab
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
  
  // More robust pattern: looks for the comment with flexible spacing
  const middlewarePattern = /([ \t]*)(\/\/\s*Add more page rewrites here[^\n]*)/;
  const middlewareMatch = content.match(middlewarePattern);
  
  if (middlewareMatch) {
    const indent = middlewareMatch[1] || '        '; // Capture only spaces/tabs, default to 8 spaces
    const newMiddleware = `${indent}// ${pageNameTitle} page
${indent}else if (pathname === '/${pageNameKebab}' || pathname === '/${pageNameKebab}/') {
${indent}  req.url = url.replace(pathname, '/src/pages/${pageNameKebab}/index.html');
${indent}} else if (pathname === '/${pageNameKebab}/index.html') {
${indent}  req.url = url.replace(pathname, '/src/pages/${pageNameKebab}/index.html');
${indent}}
${indent}
${indent}${middlewareMatch[2]}`;
    
    content = content.replace(middlewarePattern, newMiddleware);
    updateCount++;
  } else {
    warnings.push('Could not find devServerMiddleware section');
  }
  
  // 3. Write file and report results
  fs.writeFileSync(viteConfigPath, content);
  
  if (updateCount === 2) {
    console.log(`  ✅ Updated vite.config.ts (${updateCount}/2 sections)`);
  } else {
    console.log(`  ⚠️  Partially updated vite.config.ts (${updateCount}/2 sections)`);
    if (warnings.length > 0) {
      console.log(`\n  ⚠️  Warnings:`);
      warnings.forEach(warning => console.log(`     - ${warning}`));
      console.log(`\n  📝 Manual steps required:`);
      console.log(`     1. Open vite.config.ts`);
      if (updateCount === 0) {
        console.log(`     2. Add to rollupOptions.input:`);
        console.log(`        ${pageNameKebab}: path.resolve(__dirname, 'src/pages/${pageNameKebab}/index.html'),`);
      }
      if (updateCount < 2) {
        console.log(`     2. Add to devServerMiddleware before "// Add more page rewrites":`);
        console.log(`        else if (pathname === '/${pageNameKebab}' || pathname === '/${pageNameKebab}/') {`);
        console.log(`          req.url = url.replace(pathname, '/src/pages/${pageNameKebab}/index.html');`);
        console.log(`        }`);
      }
    }
  }
}

// Main function
async function createPage() {
  console.log('\n✨ Create New Page for MPA\n');

  try {
    // 1. Page name
    const pageName = await question('? Page name (kebab-case): ');
    const validation = validatePageName(pageName.trim());
    if (validation !== true) {
      console.error(`❌ ${validation}`);
      rl.close();
      process.exit(1);
    }

    const pageNameKebab = toKebabCase(pageName.trim());
    const pageNamePascal = toPascalCase(pageNameKebab);

    // Check if page already exists
    const pagePath = path.join(process.cwd(), 'src/pages', pageNameKebab);
    if (fs.existsSync(pagePath)) {
      console.error(`❌ Page "${pageNameKebab}" already exists!`);
      rl.close();
      process.exit(1);
    }

    // 2. Page title
    const pageTitle = await question('? Page title: ');

    // 3. Page description
    const pageDescription = await question('? Page description: ');

    // 4. Page-specific CSS
    const createCss = await question('? Create page-specific CSS file? (Y/n): ');
    const needsCss = !createCss.trim() || createCss.toLowerCase() === 'y';

    // 5. Components folder
    const createComponents = await question('? Create components folder? (Y/n): ');
    const needsComponents = !createComponents.trim() || createComponents.toLowerCase() === 'y';

    let componentName = '';
    if (needsComponents) {
      componentName = await question('? Initial component name (optional, press Enter to skip): ');
    }

    rl.close();

    console.log('\n📦 Creating page structure...\n');

    // Create directory
    fs.mkdirSync(pagePath, { recursive: true });
    console.log(`  ✅ Created src/pages/${pageNameKebab}/`);

    // Generate files
    generateIndexHtml(pagePath, pageNameKebab, pageTitle.trim(), pageDescription.trim());
    generateMainTsx(pagePath, pageNameKebab, pageNamePascal);
    generatePageComponent(pagePath, pageNamePascal, pageNameKebab, pageTitle.trim(), needsCss);

    if (needsCss) {
      generateCssFile(pagePath, pageNameKebab, pageNamePascal);
    }

    if (needsComponents) {
      const componentsPath = path.join(pagePath, 'components');
      fs.mkdirSync(componentsPath, { recursive: true });
      console.log(`  ✅ Created src/pages/${pageNameKebab}/components/`);

      if (componentName.trim()) {
        const compNamePascal = toPascalCase(toKebabCase(componentName.trim()));
        generateComponentFile(componentsPath, compNamePascal);
      }
    }

    // Update vite.config.ts
    updateViteConfig(pageNameKebab);

    // Success message
    console.log('\n🎉 Success! New page created!\n');
    console.log('📍 URLs:');
    console.log(`  Dev:  http://localhost:8080/${pageNameKebab}/`);
    console.log(`  Prod: /${pageNameKebab}/\n`);
    console.log('🚀 Next steps:');
    console.log('  1. npm run dev');
    console.log(`  2. Open http://localhost:8080/${pageNameKebab}/`);
    console.log(`  3. Start coding in src/pages/${pageNameKebab}/${pageNamePascal}.tsx\n`);

  } catch (error) {
    console.error('\n❌ Error creating page:', error.message);
    rl.close();
    process.exit(1);
  }
}

// Run
createPage();

